samples/config/routes.rb
AdaptiveAccountsSamples::Engine.routes.draw do
  post  "adaptive_accounts/ipn_notify" => "adaptive_accounts#ipn_notify", :as => :ipn_notify
  match "adaptive_accounts(/:action)", :controller => "adaptive_accounts", :as => :adaptive_accounts
  root :to => "adaptive_accounts#index"
end

samples/app/models/adaptive_accounts_samples/api_form_builder.rb
module AdaptiveAccountsSamples
  class APIFormBuilder < SimpleForm::FormBuilder
    def fields_for(member_name, member_object = nil, &block)
      member_object ||= ( object.send(member_name) || object.send("#{member_name}=", {}))
      member_options = object.class.members[member_name.to_sym]
      if member_options[:array]
        fields = []
        member_object.each_with_index do |obj, index|
          fields << super(member_name, obj, :index => index, &block)
        end
        fields.join.html_safe
      else
        super(member_name, member_object, &block)
      end
    end
    alias_method :simple_form_for, :fields_for
    alias_method :association, :fields_for

    def input(member_name, options = {})
      super(member_name, api_input_options(member_name, options))
    end

    def api_input_options(member_name, options = {})
      member_options      = object.class.members[member_name.to_sym]
      options[:label]   ||= member_name.to_s.underscore.humanize
      options[:wrapper] ||= :api_sample_form
      options[:required]  = !!member_options[:required] if options[:required].nil?
      if member_options[:type] < PayPal::SDK::Core::API::DataTypes::Enum
        options[:as] = ( member_options[:array] ? :check_boxes : :select )
        options[:collection] = member_options[:type].options
      elsif member_options[:type] == PayPal::SDK::Core::API::DataTypes::SimpleTypes::Boolean
        options[:as] = :select
        options[:collection] = [ true, false ]
      end
      options
    end
  end
end

samples/app/controllers/adaptive_accounts_samples/adaptive_accounts_controller.rb
require_dependency "adaptive_accounts_samples/application_controller"
require "ipaddr"

module AdaptiveAccountsSamples
  class AdaptiveAccountsController < ApplicationController
    include PayPal::SDK::AdaptiveAccounts

    def index
      redirect_to :action => :create_account
    end

    def ipn_notify
      if api.ipn_valid?(request.raw_post)
        logger.info("IPN message: VERIFIED")
        render :text => "VERIFIED"
      else
        logger.info("IPN message: INVALID")
        render :text => "INVALID"
      end
    end

    def create_account
      @create_account = api.build_create_account(params[:CreateAccountRequest] || default_api_value)
      @create_account.notificationURL ||= ipn_notify_url
      @create_account.createAccountWebOptions.returnUrl ||= adaptive_accounts_url(:create_account)
      @create_account_response = api.create_account(@create_account) if request.post?
    end

    def get_user_agreement
      @get_user_agreement = api.build_get_user_agreement(params[:GetUserAgreementRequest] || default_api_value)
      @get_user_agreement_response = api.get_user_agreement(@get_user_agreement) if request.post?
    end

    def get_verified_status
      @get_verified_status = api.build_get_verified_status(params[:GetVerifiedStatusRequest] || default_api_value)
      @get_verified_status_response = api.get_verified_status(@get_verified_status) if request.post?
    end

    def add_bank_account
      @add_bank_account = api.build_add_bank_account(params[:AddBankAccountRequest] || default_api_value)
      @add_bank_account_response = api.add_bank_account(@add_bank_account) if request.post?
    end

    def add_payment_card
      @add_payment_card = api.build_add_payment_card(params[:AddPaymentCardRequest] || default_api_value)
      @add_payment_card_response = api.add_payment_card(@add_payment_card) if request.post?
    end

    def set_funding_source_confirmed
      @set_funding_source_confirmed = api.build_set_funding_source_confirmed(params[:SetFundingSourceConfirmedRequest] || default_api_value)
      @set_funding_source_confirmed_response = api.set_funding_source_confirmed(@set_funding_source_confirmed) if request.post?
    end

    def check_compliance_status
      @check_compliance_status = api.build_check_compliance_status(params[:CheckComplianceStatusRequest] || default_api_value)
      @check_compliance_status_response = api.check_compliance_status(@check_compliance_status) if request.post?
    end


    private

    def api
      @api ||= API.new( :device_ipaddress => IPAddr.new(request.remote_ip).native.to_s )
    end
  end
end

samples/app/controllers/adaptive_accounts_samples/application_controller.rb
module AdaptiveAccountsSamples
  class ApplicationController < ActionController::Base

    def default_api_value
      t("#{service_name}.#{service_action}", :default => {})
    end

    def service_name
      params[:controller].gsub(/^.*\//, "")
    end

    def service_action
      params[:action]
    end
    helper_method :service_action, :service_name

  end
end

samples/app/helpers/adaptive_accounts_samples/adaptive_accounts_helper.rb
module AdaptiveAccountsSamples
  module AdaptiveAccountsHelper
  end
end

samples/app/helpers/adaptive_accounts_samples/application_helper.rb
module AdaptiveAccountsSamples
  module ApplicationHelper
    def active_li(display, link_path, options = {})
      active_menu = options.delete(:match_path) ? request.path =~ Regexp.new(link_path) : request.path == link_path
      content_tag(:li, :class => active_menu ? "active" : "") do
        link_to(display, link_path, options)
      end
    end

    def active_li_regexp(display, link_path, options = {})
      active_li(display, link_path, options.merge(:match_path => true))
    end

    def api_form_for(object, *args, &block)
      options         = args.extract_options!
      options[:as]  ||= api_class_name(object.class)
      simple_form_for(object, *(args << options.merge(:builder => APIFormBuilder, :wrapper => :api_sample_form)), &block)
    end

    def generate_code(api_request, api_response)
      request_hash= api_request.to_hash(:namespace => false, :attribute => false)
      request_hash.delete(:Version)
      # request_hash  = get_dotted_hash(request_hash)
      response_hash = api_response.to_hash(:namespace => false, :attribute => false)
      ruby_code   = render("ruby_code.rb", :api_request => api_request, :api_response => api_response, :request_hash => request_hash, :response_hash => response_hash)
      ruby_code.html_safe
    end

    def get_dotted_hash(hash, prefix = "", values = {})
      max_lenght  = Hash[hash.select{|k, v| !(v.is_a? Hash or v.is_a? Array) }].keys.map(&:size).max
      hash.each do |key, value|
        if value.is_a? Hash
          get_dotted_hash(value, "#{prefix}#{key}.", values)
        elsif value.is_a? Array and value[0].is_a? Hash
          value.each_with_index do |array_value, index|
            get_dotted_hash(array_value, "#{prefix}#{key}[#{index}].", values)
          end
        elsif !value.nil?
          k = sprintf("%s%-#{max_lenght}s", prefix, key)
          values[k] = value
        end
      end
      values
    end

    def format_hash(hash)
      entries = hash.map do |key, value|
        "#{key.to_sym.inspect} => " +
          if value.is_a? Hash and value.size > 0
            format_hash(value)
          elsif value.is_a? Array and value[0].is_a? Hash
            "[" + value.map{|v| format_hash(v) }.join(",") + "]"
          else
            value.to_json
          end
      end
      indent_hash_entries(entries)
    end

    def indent_hash_entries(entries)
      if entries.size > 0
        "{\n" + entries.join(",\n").gsub(/^/, "  ") + " }"
      else
        "{}"
      end
    end

    def api_class_name(klass)
      klass.name.gsub(/^.*::/, "")
    end
  end
end

samples/app/views/adaptive_accounts_samples/adaptive_accounts/_address.html.haml
= f.input :line1
= f.input :line2
= f.input :city
= f.input :state
= f.input :postalCode
= f.input :countryCode, :as => :string

samples/app/views/adaptive_accounts_samples/adaptive_accounts/_name.html.haml
= f.input :salutation
= f.input :firstName
= f.input :middleName
= f.input :lastName
= f.input :suffix

samples/app/views/adaptive_accounts_samples/adaptive_accounts/_sidebar.html.haml
.well.well-mini
  %ul.nav.nav-list.bs-docs-sidenav
    = active_li "Create",                     adaptive_accounts_path(:create_account)
    = active_li "Add Bank",                   adaptive_accounts_path(:add_bank_account)
    = active_li "Add Payment Card",           adaptive_accounts_path(:add_payment_card)
    = active_li "Get User Agreement",         adaptive_accounts_path(:get_user_agreement)
    = active_li "Set Funding Source Confirm", adaptive_accounts_path(:set_funding_source_confirmed)
    = active_li "Get Verified Status",        adaptive_accounts_path(:get_verified_status)

samples/app/views/adaptive_accounts_samples/adaptive_accounts/_web_options.html.haml
= f.input :returnUrl
= f.input :returnUrlDescription
= f.input :cancelUrl
= f.input :cancelUrlDescription

samples/app/views/adaptive_accounts_samples/adaptive_accounts/add_bank_account.html.haml
= api_form_for @add_bank_account, :url => adaptive_accounts_path(:add_bank_account) do |f|

  .row
    .span5
      %legend Add bank account request
      = f.input :emailAddress
      = f.input :accountId
      = f.input :createAccountKey
      = f.input :bankCountryCode
      = f.input :bankName
      = f.input :routingNumber
      = f.input :bankAccountType
      = f.input :bankAccountNumber
      = f.input :confirmationType
      = f.input :iban
      = f.input :clabe
      = f.input :bsbNumber
      = f.input :branchLocation
      = f.input :sortCode
    .span5
      %legend -
      = f.input :bankTransitNumber
      = f.input :institutionNumber
      = f.input :branchCode
      = f.input :agencyNumber
      = f.input :bankCode
      = f.input :ribKey
      = f.input :controlDigit
      = f.input :accountHolderDateOfBirth
      %legend Web Options
      = f.fields_for :webOptions do |opt|
        = render 'web_options', :f => opt



  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @add_bank_account_response
  = render 'api_response', :request => @add_bank_account, :response => @add_bank_account_response
  = link_to "Redirect Url", @add_bank_account_response.redirectURL if @add_bank_account_response.redirectURL

samples/app/views/adaptive_accounts_samples/adaptive_accounts/add_payment_card.html.haml
= api_form_for @add_payment_card, :url => adaptive_accounts_path(:add_payment_card) do |f|

  .row
    .span5
      %legend Add payment card request
      = f.input :emailAddress
      = f.input :accountId
      = f.input :createAccountKey
      %legend Name on card
      = f.fields_for :nameOnCard do |name|
        = render 'name', :f => name
      %legend Billing address
      = f.fields_for :billingAddress do |address|
        = render 'address', :f => address

    .span5
      %legend Card
      = f.input :cardNumber
      = f.input :cardType
      = f.input :cardOwnerDateOfBirth
      = f.input :cardVerificationNumber
      = f.input :issueNumber
      = f.input :confirmationType
      %legend Expire Date
      = f.fields_for :expirationDate do |edate|
        = edate.input :month, :as => :select, :collection => (1..12).to_a
        = edate.input :year
      %legend Web Options
      = f.fields_for :webOptions do |opt|
        = render 'web_options', :f => opt


  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @add_payment_card_response
  = render 'api_response', :request => @add_payment_card, :response => @add_payment_card_response
  = link_to "Redirect Url", @add_payment_card_response.redirectURL if @add_payment_card_response.redirectURL

samples/app/views/adaptive_accounts_samples/adaptive_accounts/create_account.html.haml
= api_form_for @create_account, :url => adaptive_accounts_path(:create_account) do |f|

  .row
    .span5
      %legend Create account request
      = f.input :accountType, :as => :select, :collection => [ "Personal", "Premier", "Business" ]
      = f.fields_for :name do |name|
        = render 'name', :f => name
      = f.input :dateOfBirth
      %legend Address
      = f.fields_for :address do |address|
        = render "address", :f => address
      = f.input :contactPhoneNumber
      = f.input :homePhoneNumber
      = f.input :mobilePhoneNumber
      = f.input :currencyCode
      = f.input :citizenshipCountryCode
      = f.input :preferredLanguageCode
      = f.input :notificationURL
      = f.input :emailAddress
      = f.input :registrationType, :as => :select, :collection => [ "Web", "Mobile" ]
      %legend Web options
      = f.fields_for :createAccountWebOptions do |opt|
        = opt.input :returnUrl
        = opt.input :showAddCreditCard
        = opt.input :showMobileConfirm
        = opt.input :returnUrlDescription
        = opt.input :useMiniBrowser
      = f.input :suppressWelcomeEmail
      = f.input :performExtraVettingOnThisAccount
      = f.input :taxId
      = f.input :partnerField1
      = f.input :partnerField2
      = f.input :partnerField3
      = f.input :partnerField4
      = f.input :partnerField5
    .span5
      = f.fields_for :businessInfo do |bi|
        %legend Business info
        = bi.input :businessName
        = bi.fields_for :businessAddress do |address|
          = render 'address', :f => address
        = bi.input :workPhone
        = bi.input :category
        = bi.input :subCategory
        = bi.input :merchantCategoryCode
        = bi.input :doingBusinessAs
        = bi.input :customerServicePhone
        = bi.input :customerServiceEmail
        = bi.input :disputeEmail
        = bi.input :webSite
        = bi.input :companyId
        = bi.input :dateOfEstablishment
        = bi.input :businessType
        = bi.input :businessSubtype
        = bi.input :incorporationId
        = bi.input :averagePrice
        = bi.input :averageMonthlyVolume
        = bi.input :percentageRevenueFromOnline
        = bi.input :salesVenue
        = bi.input :salesVenueDesc
        = bi.input :vatId
        = bi.input :vatCountryCode
        = bi.input :commercialRegistrationLocation

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @create_account_response
  = render 'api_response', :request => @create_account, :response => @create_account_response
  = link_to "Redirect Url", @create_account_response.redirectURL if @create_account_response.redirectURL

samples/app/views/adaptive_accounts_samples/adaptive_accounts/get_user_agreement.html.haml
= api_form_for @get_user_agreement, :url => adaptive_accounts_path(:get_user_agreement) do |f|

  .row
    .span5
      %legend get user aggrement request
      = f.input :createAccountKey
      = f.input :countryCode, :as => :string
      = f.input :languageCode

    .span5
      %legend Items


  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @get_user_agreement_response
  = render 'api_response', :request => @get_user_agreement, :response => @get_user_agreement_response

samples/app/views/adaptive_accounts_samples/adaptive_accounts/get_verified_status.html.haml
= api_form_for @get_verified_status, :url => adaptive_accounts_path(:get_verified_status) do |f|

  .row
    .span5
      %legend Get verified status request
      = f.input :emailAddress
      = f.input :matchCriteria, :as => :select, :collection => [ "NAME", "NONE" ]
      = f.input :firstName
      = f.input :lastName

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @get_verified_status_response
  = render 'api_response', :request => @get_verified_status, :response => @get_verified_status_response

samples/app/views/adaptive_accounts_samples/adaptive_accounts/set_funding_source_confirmed.html.haml
= api_form_for @set_funding_source_confirmed, :url => adaptive_accounts_path(:set_funding_source_confirmed) do |f|

  .row
    .span5
      %legend Set funding source confirmed request
      = f.input :accountId
      = f.input :emailAddress
      = f.input :fundingSourceKey

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @set_funding_source_confirmed_response
  = render 'api_response', :request => @set_funding_source_confirmed, :response => @set_funding_source_confirmed_response

samples/app/views/adaptive_accounts_samples/application/_api_response.html.haml
%div#response
  %p
    %b Ruby Code:
    = find_and_preserve CodeRay.scan(generate_code(request, response), "ruby").div.html_safe
  %p
    %b Response:
    = find_and_preserve CodeRay.scan(format_hash(response.to_hash(:attribute => false, :namespace => false)), "ruby").div.html_safe

samples/app/views/adaptive_accounts_samples/application/_hash_block.rb.erb
<% hash.each do |key, value| -%>
  <% if value.is_a? Hash -%>
<%= space %><%= key %> do
<%= render "hash_block.rb", :space => space + "  ", :hash => value %>
<%= space %>end
  <% elsif value.is_a? Array and value[0].is_a? Hash -%>
    <% value.each_with_index do |array_value, index| -%>
<%= space %><%= key %>[<%= index %>] do
<%= render "hash_block.rb", :space => space + "  ", :hash => array_value %>
<%= space %>end
    <% end -%>
  <% else -%>
<%= space %>self.<%= key %> = <%= value.to_json.html_safe %>
  <% end -%>
<% end -%>

samples/app/views/adaptive_accounts_samples/application/_header.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .pull-right
        = link_to "Source on GitHub", "https://github.com/paypal/adaptiveaccounts-sdk-ruby", :class => "btn btn-small"
        %span.btn.btn-info.btn-small.disabled Click Submit to Generate Code !
      %a.brand{:href => "#"} PayPal SDK
      .nav-collapse.collapse
        %ul.nav
          = active_li_regexp "Adaptive Accounts", adaptive_accounts_path

samples/app/views/adaptive_accounts_samples/application/_ruby_code.rb.erb
require 'paypal-sdk-<%= service_name.gsub("_", "") %>'
@api = PayPal::SDK::<%= service_name.camelize %>::API.new( :device_ipaddress => "127.0.0.1" )

# Build request object
@<%= service_action %> = @api.build_<%= service_action %>(<%= format_hash(request_hash).html_safe %>)

# Make API call & get response
@<%= service_action %>_response = @api.<%= service_action %>(@<%= service_action %>)

# Access Response
if @<%= service_action %>_response.success?
<% api_response.members.keys.each do |name| -%>
  <% unless [:xmlns, :type, :responseEnvelope, :error].include? name -%>
  @<%= service_action %>_response.<%= name %>
  <% end %>
<% end -%>
else
  @<%= service_action %>_response.error
end

samples/app/views/adaptive_accounts_samples/application/_sidebar.html.erb
<ul class="nav nav-list bs-docs-sidenav ">
  <%= active_li "Home",  "/" %>
</ul>

samples/app/views/adaptive_accounts_samples/application/_token.html.haml
%legend Autherization
.control-group.string.optional
  = label_tag :token, "Token", :class => "string optional control-label"
  .controls
    = text_field_tag :token, params[:token] || @api.config.token

.control-group.string.optional
  = label_tag :token_secret, "Token Secret", :class => "string optional control-label"
  .controls
    = text_field_tag :token_secret, params[:token_secret] || @api.config.token_secret

samples/app/views/layouts/adaptive_accounts_samples/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "#{service_action.humanize} | #{service_name.humanize}"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    = stylesheet_link_tag    "adaptive_accounts_samples/application", :media => "all"
  %body
    = render "header"
    .container
      .row
        .span2= render "sidebar"
        .span10= yield
    = javascript_include_tag "adaptive_accounts_samples/application"